ECHO OFF

ECHO This will take few mins...
pause

ECHO deleting unwanted dvi files...
del /S *.dvi 

ECHO deleting unwanted aux files...
del /S *.aux

ECHO deleting unwanted bbl files...
del /S *.bbl

ECHO deleting unwanted log files...
del /S *.log

ECHO deleting unwanted blg files...
del /S *.blg

ECHO deleting unwanted out files...
del /S *.out

ECHO deleting unwanted spl files...
del /S *.spl

ECHO deleting unwanted ps files...
del /S *.ps

ECHO All unwanted files are deleted...
pause
